name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"  # Esto hace que se ejecute todos los días a las 18:00 UTC
  workflow_dispatch:  # Esto permite ejecutar el flujo manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest  # Se ejecuta en un entorno Ubuntu
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Se hace un checkout del código del repositorio
      - name: Generate 3D Profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1  # Usamos la acción que genera el gráfico 3D
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de acceso
          USERNAME: ${{ github.repository_owner }}  # Nombre de usuario de GitHub
      - name: Commit & Push the Generated Image
        run: |
          git config user.name arcanus47  # Configuramos el nombre de usuario para los commits
          git config user.email cheremycheco@gmail.com  # Configuramos el email
          git add -A .  # Agregamos todos los cambios
          git commit -m "generated"  # Hacemos un commit con el mensaje "generated"
          git push  # Empujamos los cambios al repositorio
